//+------------------------------------------------------------------+
//|                                              XAU_GoldAdvisor_v2.mq4 |
//|          Обновлённая версия советника: проверка минимального SL/TP |
//+------------------------------------------------------------------+
#property copyright "Generated by GitHub Copilot"
#property link      ""
#property version   "1.10"
#property strict
#property description "EA для торговли XAUUSD с улучшенной проверкой минимального расстояния StopLoss/TakeProfit"

input double Lots = 0.10;                     // Размер лота
input int    MagicNumber = 20260521;          // Магический номер ордера
input int    FastMAPeriod = 50;               // Быстрая EMA
input int    SlowMAPeriod = 200;              // Медленная EMA
input int    ATRPeriod = 14;                  // Период ATR
input double ATRMultiplierSL = 1.8;           // Множитель для Stop Loss
input double ATRMultiplierTP = 2.8;           // Множитель для Take Profit
input int    MaxSpreadPoints = 35;            // Максимальный спред в пунктах
input bool   UseTimeFilter = true;            // Использовать торговый фильтр по времени
input int    StartHour = 8;                   // Начало торгового окна (серверное время)
input int    EndHour = 21;                    // Конец торгового окна (серверное время)
input bool   UseTrailingStop = true;           // Включить трейлинг-стоп
input int    TrailingStartPoints = 80;        // Начинать трейлинг после X пунктов в прибыли
input int    TrailingStepPoints = 20;         // Шаг трейлинга
input bool   UseMaxTradesPerDay = true;       // Ограничить число сделок в день
input int    MaxTradesPerDay = 2;             // Максимум сделок в день

datetime lastBarTime = 0;

//+------------------------------------------------------------------+
int OnInit()
  {
   if (StringFind(Symbol(),"XAU") == -1 && StringFind(Symbol(),"GOLD") == -1)
     {
      Print("[XAU_GoldAdvisor_v2] Рекомендуется запускать EA на XAUUSD или символе золота.");
     }
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
void OnTick()
  {
   RefreshRates();

   if (!IsTradeAllowed())
      return;

   if (UseTimeFilter && !IsWithinTradeTime())
      return;

   if (!IsNewBar())
      return;

   ManageOpenOrders();

   if (CountOpenOrders() == 0)
      TryOpenNewOrder();
  }

//+------------------------------------------------------------------+
bool IsTradeAllowed()
  {
   if (IsTradeContextBusy())
      return(false);

   int spread = MarketInfo(Symbol(), MODE_SPREAD);
   if (spread > MaxSpreadPoints)
     {
      PrintFormat("[XAU_GoldAdvisor_v2] Спред %d превышает допустимый %d.", spread, MaxSpreadPoints);
      return(false);
     }

   if (AccountFreeMargin() < 1000)
     {
      Print("[XAU_GoldAdvisor_v2] Недостаточно свободной маржи для торговли.");
      return(false);
     }

   return(true);
  }

//+------------------------------------------------------------------+
bool IsWithinTradeTime()
  {
   int hour = TimeHour(TimeCurrent());
   if (StartHour < EndHour)
      return(hour >= StartHour && hour < EndHour);
   return(hour >= StartHour || hour < EndHour);
  }

//+------------------------------------------------------------------+
bool IsNewBar()
  {
   datetime currentBar = iTime(Symbol(), PERIOD_H1, 0);
   if (currentBar == lastBarTime)
      return(false);

   lastBarTime = currentBar;
   return(true);
  }

//+------------------------------------------------------------------+
int CountOpenOrders()
  {
   int count = 0;
   for (int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if (OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if (OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
            count++;
        }
     }
   return(count);
  }

//+------------------------------------------------------------------+
void ManageOpenOrders()
  {
   for (int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if (!OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
         continue;
      if (OrderMagicNumber() != MagicNumber || OrderSymbol() != Symbol())
         continue;

      if (OrderType() == OP_BUY)
         ManageBuyOrder();
      else if (OrderType() == OP_SELL)
         ManageSellOrder();
     }
  }

//+------------------------------------------------------------------+
void ManageBuyOrder()
  {
   RefreshRates();
   double bid = MarketInfo(Symbol(), MODE_BID);
   double newStop = bid - TrailingStepPoints * Point;
   if (UseTrailingStop && bid - OrderOpenPrice() >= TrailingStartPoints * Point)
     {
      if (OrderStopLoss() == 0 || newStop > OrderStopLoss())
        {
         if (newStop < OrderOpenPrice() + 10 * Point)
            newStop = OrderOpenPrice() + 10 * Point;
         if (!OrderModify(OrderTicket(), OrderOpenPrice(), NormalizeDouble(newStop, Digits), OrderTakeProfit(), 0, clrGreen))
            PrintFormat("[XAU_GoldAdvisor_v2] Ошибка установки трейлинг-стопа BUY: %s", GetLastError());
        }
     }
  }

//+------------------------------------------------------------------+
void ManageSellOrder()
  {
   RefreshRates();
   double ask = MarketInfo(Symbol(), MODE_ASK);
   double newStop = ask + TrailingStepPoints * Point;
   if (UseTrailingStop && OrderOpenPrice() - ask >= TrailingStartPoints * Point)
     {
      if (OrderStopLoss() == 0 || newStop < OrderStopLoss())
        {
         if (newStop > OrderOpenPrice() - 10 * Point)
            newStop = OrderOpenPrice() - 10 * Point;
         if (!OrderModify(OrderTicket(), OrderOpenPrice(), NormalizeDouble(newStop, Digits), OrderTakeProfit(), 0, clrRed))
            PrintFormat("[XAU_GoldAdvisor_v2] Ошибка установки трейлинг-стопа SELL: %s", GetLastError());
        }
     }
  }

//+------------------------------------------------------------------+
void TryOpenNewOrder()
  {
   RefreshRates();
   double fastEMA = iMA(Symbol(), PERIOD_H1, FastMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
   double slowEMA = iMA(Symbol(), PERIOD_H1, SlowMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
   double prevFastEMA = iMA(Symbol(), PERIOD_H1, FastMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 2);
   double prevSlowEMA = iMA(Symbol(), PERIOD_H1, SlowMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 2);
   double atr = iATR(Symbol(), PERIOD_H1, ATRPeriod, 1);

   if (atr <= 0)
     {
      Print("[XAU_GoldAdvisor_v2] Невозможно получить значение ATR.");
      return;
     }

   double stopLoss = NormalizeDouble(atr * ATRMultiplierSL, Digits);
   double takeProfit = NormalizeDouble(atr * ATRMultiplierTP, Digits);
   if (stopLoss < 30 * Point)
      stopLoss = 30 * Point;
   if (takeProfit < 60 * Point)
      takeProfit = 60 * Point;

   int todayTrades = CountTodayTrades();
   if (UseMaxTradesPerDay && todayTrades >= MaxTradesPerDay)
     {
      PrintFormat("[XAU_GoldAdvisor_v2] Достигнут лимит сделок за день: %d", MaxTradesPerDay);
      return;
     }

   if (prevFastEMA < prevSlowEMA && fastEMA > slowEMA)
     OpenBuy(stopLoss, takeProfit);
   else if (prevFastEMA > prevSlowEMA && fastEMA < slowEMA)
     OpenSell(stopLoss, takeProfit);
  }

//+------------------------------------------------------------------+
void OpenBuy(double stopLoss, double takeProfit)
  {
   RefreshRates();
   double ask = MarketInfo(Symbol(), MODE_ASK);
   double sl = NormalizeDouble(ask - stopLoss, Digits);
   double tp = NormalizeDouble(ask + takeProfit, Digits);

   // Проверка минимального расстояния до SL/TP у брокера
   int stopLevelPoints = MarketInfo(Symbol(), MODE_STOPLEVEL);
   double minDistance = (stopLevelPoints + 1) * Point; // добавляем запас 1 пункт
   if (ask - sl < minDistance)
     {
      sl = NormalizeDouble(ask - minDistance, Digits);
      PrintFormat("[XAU_GoldAdvisor_v2] SL скорректирован до минимального расстояния: %G", sl);
     }
   if (tp - ask < minDistance)
     {
      tp = NormalizeDouble(ask + minDistance, Digits);
      PrintFormat("[XAU_GoldAdvisor_v2] TP скорректирован до минимального расстояния: %G", tp);
     }

   int ticket = OrderSend(Symbol(), OP_BUY, Lots, ask, 3, sl, tp, "XAU Gold Advisor v2", MagicNumber, 0, clrBlue);
   if (ticket < 0)
      PrintFormat("[XAU_GoldAdvisor_v2] Ошибка открытия BUY: %s", GetLastError());
   else
      PrintFormat("[XAU_GoldAdvisor_v2] Открыт BUY %s, SL=%G, TP=%G", Symbol(), sl, tp);
  }

//+------------------------------------------------------------------+
void OpenSell(double stopLoss, double takeProfit)
  {
   RefreshRates();
   double bid = MarketInfo(Symbol(), MODE_BID);
   double sl = NormalizeDouble(bid + stopLoss, Digits);
   double tp = NormalizeDouble(bid - takeProfit, Digits);

   int stopLevelPoints = MarketInfo(Symbol(), MODE_STOPLEVEL);
   double minDistance = (stopLevelPoints + 1) * Point;
   if (sl - bid < minDistance)
     {
      sl = NormalizeDouble(bid + minDistance, Digits);
      PrintFormat("[XAU_GoldAdvisor_v2] SL скорректирован до минимального расстояния: %G", sl);
     }
   if (bid - tp < minDistance)
     {
      tp = NormalizeDouble(bid - minDistance, Digits);
      PrintFormat("[XAU_GoldAdvisor_v2] TP скорректирован до минимального расстояния: %G", tp);
     }

   int ticket = OrderSend(Symbol(), OP_SELL, Lots, bid, 3, sl, tp, "XAU Gold Advisor v2", MagicNumber, 0, clrRed);
   if (ticket < 0)
      PrintFormat("[XAU_GoldAdvisor_v2] Ошибка открытия SELL: %s", GetLastError());
   else
      PrintFormat("[XAU_GoldAdvisor_v2] Открыт SELL %s, SL=%G, TP=%G", Symbol(), sl, tp);
  }

//+------------------------------------------------------------------+
int CountTodayTrades()
  {
   int count = 0;
   datetime now = TimeCurrent();

   for (int i = OrdersHistoryTotal() - 1; i >= 0; i--)
     {
      if (OrderSelect(i, SELECT_BY_POS, MODE_HISTORY))
        {
         if (OrderMagicNumber() != MagicNumber || OrderSymbol() != Symbol())
            continue;
         datetime closeTime = OrderCloseTime();
         if (closeTime == 0)
            continue;
         if (TimeDay(closeTime) == TimeDay(now) && TimeMonth(closeTime) == TimeMonth(now) && TimeYear(closeTime) == TimeYear(now))
            count++;
        }
     }

   for (int j = OrdersTotal() - 1; j >= 0; j--)
     {
      if (OrderSelect(j, SELECT_BY_POS, MODE_TRADES))
        {
         if (OrderMagicNumber() != MagicNumber || OrderSymbol() != Symbol())
            continue;
         datetime openTime = OrderOpenTime();
         if (TimeDay(openTime) == TimeDay(now) && TimeMonth(openTime) == TimeMonth(now) && TimeYear(openTime) == TimeYear(now))
            count++;
        }
     }

   return(count);
  }

//+------------------------------------------------------------------+
